// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Dart bindings for the gcs_ffi C API
class GcsBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  GcsBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  GcsBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// \brief Creates the session/store from a serialized gcs.chat.GcsConfig
  /// (codec-tagged bytes — D-29).
  ///
  /// The codec is bound to the store here and is immutable for the store's
  /// lifetime; Phase 1 accepts CODEC_PROTOBUF only (else the call fails as an
  /// unsupported codec). On success the session pre-joins the smoke-topic set
  /// so the pushed room list is non-empty.
  ///
  /// Thread-safe via global mutex; idempotent — when a session already exists
  /// its handle is returned again. Returns NULL on failure (invalid arguments,
  /// config parse failure, unsupported codec, or initialization failure). Null
  /// configBytes is invalid.
  ///
  /// \param[in] configBytes   Serialized gcs.chat.GcsConfig bytes (caller owns
  /// the buffer for the call duration only).
  /// \param[in] configLength  Length of configBytes in bytes; zero is invalid.
  /// \return Opaque session handle on success, NULL on failure.
  ffi.Pointer<GcsSession> gcs_init(
    ffi.Pointer<ffi.Uint8> configBytes,
    int configLength,
  ) {
    return _gcs_init(configBytes, configLength);
  }

  late final _gcs_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GcsSession> Function(ffi.Pointer<ffi.Uint8>, ffi.Size)
        >
      >('gcs_init');
  late final _gcs_init = _gcs_initPtr
      .asFunction<
        ffi.Pointer<GcsSession> Function(ffi.Pointer<ffi.Uint8>, int)
      >();

  /// \brief Publishes a codec-encoded payload to a topic (D-27: commands are
  /// topic publishes).
  ///
  /// Payloads are bytes + length, never char*. On the command topic the payload
  /// must parse as gcs.chat.GcsCommand; C++ validates, stamps authority fields,
  /// and pushes resulting GcsEvent bytes to the subscribed port. Parse failure
  /// returns GCS_ERROR_INVALID_ARGUMENT and pushes an ErrorNotice carrying the
  /// raw error string. Phase 1 accepts the command topic only.
  ///
  /// The caller-owned payload buffer is copied inside the call; no pointer to
  /// caller memory is retained after return.
  ///
  /// \param[in] session         Handle returned by a successful init.
  /// \param[in] topic           NUL-terminated topic name to publish to.
  /// \param[in] payloadBytes    Codec-encoded payload bytes (caller owns the
  /// buffer for the call duration only).
  /// \param[in] payloadLength   Length of payloadBytes in bytes; zero is invalid.
  /// \return GCS_OK on success; GCS_ERROR_INVALID_ARGUMENT on null/mismatched
  /// arguments or a parse failure; GCS_ERROR_NOT_RUNNING when the
  /// session is not running; GCS_ERROR_GENERIC otherwise.
  int gcs_publish(
    ffi.Pointer<GcsSession> session,
    ffi.Pointer<ffi.Char> topic,
    ffi.Pointer<ffi.Uint8> payloadBytes,
    int payloadLength,
  ) {
    return _gcs_publish(session, topic, payloadBytes, payloadLength);
  }

  late final _gcs_publishPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<GcsSession>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
          )
        >
      >('gcs_publish');
  late final _gcs_publish = _gcs_publishPtr
      .asFunction<
        int Function(
          ffi.Pointer<GcsSession>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  /// \brief Registers the Dart NativePort (int64_t send port) that receives
  /// pushed GcsEvent bytes for the topic (D-05/D-26 push-not-pull — messages,
  /// room-list, readiness, and raw error strings all arrive here).
  ///
  /// On registration, immediately pushes the current RoomList and a
  /// Readiness(ready=true) event. Phase 1 delivers all events to the port as a
  /// single event stream regardless of the topic argument; topic-graded
  /// delivery is a later-phase refinement. No pull-style query function exists.
  ///
  /// \param[in] session    Handle returned by a successful init.
  /// \param[in] topic      NUL-terminated topic name the port subscribes to.
  /// \param[in] dartPort   Dart NativePort (send port) id; zero is invalid.
  /// \return GCS_OK on success; GCS_ERROR_INVALID_ARGUMENT on null/mismatched
  /// arguments or a zero port; GCS_ERROR_NOT_RUNNING when the session
  /// is not running.
  int gcs_subscribe(
    ffi.Pointer<GcsSession> session,
    ffi.Pointer<ffi.Char> topic,
    int dartPort,
  ) {
    return _gcs_subscribe(session, topic, dartPort);
  }

  late final _gcs_subscribePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<GcsSession>,
            ffi.Pointer<ffi.Char>,
            ffi.Int64,
          )
        >
      >('gcs_subscribe');
  late final _gcs_subscribe = _gcs_subscribePtr
      .asFunction<
        int Function(ffi.Pointer<GcsSession>, ffi.Pointer<ffi.Char>, int)
      >();

  /// \brief Tears down the session (unregisters the port before freeing).
  ///
  /// Clears the registered Dart port first, then shuts down and frees the
  /// session. Idempotent and null-tolerant: null or mismatched handles are a
  /// no-op (an opaque-handle equality check prevents double-free and
  /// use-after-free).
  ///
  /// \param[in] session  Handle returned by a successful init; may be NULL.
  void gcs_shutdown(ffi.Pointer<GcsSession> session) {
    return _gcs_shutdown(session);
  }

  late final _gcs_shutdownPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GcsSession>)>>(
        'gcs_shutdown',
      );
  late final _gcs_shutdown = _gcs_shutdownPtr
      .asFunction<void Function(ffi.Pointer<GcsSession>)>();
}

final class GcsSession extends ffi.Opaque {}

/// C status codes returned by the int-valued ABI functions.
abstract class GcsStatus {
  static const int GCS_OK = 0;
  static const int GCS_ERROR_GENERIC = 1;
  static const int GCS_ERROR_INVALID_ARGUMENT = 2;
  static const int GCS_ERROR_NOT_RUNNING = 3;
  static const int GCS_ERROR_UNSUPPORTED_CODEC = 4;
}
